# Generated by Django 6.0.1 on 2026-02-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_created_dc23ea_idx',
            old_name='core_auditl_created_7a9f57_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_29a2bf_idx',
            old_name='core_auditl_action_87cb84_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_entity_a54c8a_idx',
            old_name='core_auditl_entity_8cbfef_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_i_41600a_idx',
            old_name='core_auditl_actor_i_eb3a02_idx',
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['branch', 'is_active'], name='core_device_branch__f95e04_idx'),
        ),
    ]
