# Generated by Django 6.0.1 on 2026-02-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncevent',
            new_name='sync_syncev_device__1a066c_idx',
            old_name='syncevent_device_created_idx',
        ),
        migrations.RenameIndex(
            model_name='syncevent',
            new_name='sync_syncev_branch__a7cae0_idx',
            old_name='syncevent_branch_created_idx',
        ),
        migrations.RenameIndex(
            model_name='syncoutbox',
            new_name='sync_syncou_branch__1ef32c_idx',
            old_name='syncoutbox_branch_id_idx',
        ),
        migrations.RenameIndex(
            model_name='syncoutbox',
            new_name='sync_syncou_entity_318ce6_idx',
            old_name='syncoutbox_entity_id_idx',
        ),
    ]
