# Generated by ChatGPT

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stocktransfer_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="minimum_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="product",
            name="preferred_supplier",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="inventory.supplier"),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("severity", models.CharField(choices=[("low", "Low"), ("critical", "Critical")], max_length=16)),
                ("current_quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("threshold_quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("suggested_reorder_quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("is_read", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.branch")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.product")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.warehouse")),
            ],
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(fields=["branch", "is_read", "severity"], name="inventory_in_branch__a35d43_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(fields=["warehouse", "product"], name="inventory_in_warehou_13a4f5_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(fields=["branch", "updated_at"], name="inventory_in_branch__3fdb70_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventoryalert",
            constraint=models.UniqueConstraint(condition=models.Q(("resolved_at__isnull", True)), fields=("branch", "warehouse", "product"), name="uniq_open_alert_per_product_warehouse"),
        ),
    ]
