# Generated by Django 6.0.1 on 2026-02-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_intelligence_alerts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='inventory_c_branch__ab39bd_idx',
            old_name='category_branch_active_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='inventory_c_parent__a38b2c_idx',
            old_name='category_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryalert',
            new_name='inventory_i_branch__4bbb45_idx',
            old_name='inventory_in_branch__a35d43_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryalert',
            new_name='inventory_i_warehou_3c5ca4_idx',
            old_name='inventory_in_warehou_13a4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryalert',
            new_name='inventory_i_branch__017267_idx',
            old_name='inventory_in_branch__3fdb70_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_branch__77a8c7_idx',
            old_name='product_branch_barcode_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_branch__4c740b_idx',
            old_name='product_branch_active_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='inventory_p_branch__51d1b9_idx',
            old_name='inventory_pu_branch__34e1df_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='inventory_p_supplie_80088d_idx',
            old_name='inventory_pu_supplie_469c0e_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderline',
            new_name='inventory_p_purchas_aa823f_idx',
            old_name='inventory_pu_purchase_ebf860_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderline',
            new_name='inventory_p_product_c8831a_idx',
            old_name='inventory_pu_product_a1ac0f_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmove',
            new_name='inventory_s_warehou_f5591e_idx',
            old_name='stockmove_wh_prod_created_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmove',
            new_name='inventory_s_branch__ad802a_idx',
            old_name='stockmove_branch_created_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmove',
            new_name='inventory_s_source__833ef8_idx',
            old_name='stockmove_source_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_branch__c0f061_idx',
            old_name='inventory_st_branch__c3f870_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='inventory_s_source__770ddc_idx',
            old_name='inventory_st_source__83a7de_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransferline',
            new_name='inventory_s_transfe_60e28a_idx',
            old_name='inventory_st_transfer_96b7ed_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransferline',
            new_name='inventory_s_product_0ffd76_idx',
            old_name='inventory_st_product_814f35_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='inventory_s_branch__061fcc_idx',
            old_name='inventory_su_branch__69bd64_idx',
        ),
        migrations.RenameIndex(
            model_name='suppliercontact',
            new_name='inventory_s_supplie_7a6c03_idx',
            old_name='inventory_su_supplie_0f38fd_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='inventory_w_branch__89a748_idx',
            old_name='warehouse_branch_active_idx',
        ),
    ]
