# Generated by Django 5.1.1 on 2026-03-06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_productunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBundle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("standalone_sku", models.CharField(blank=True, max_length=64, null=True)),
                ("custom_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.branch")),
                (
                    "parent_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bundles",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["branch", "is_active"], name="inventory_pr_branch__f8a8f6_idx"), models.Index(fields=["branch", "parent_product"], name="inventory_pr_branch__e89cc8_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("branch", "code"), name="uniq_bundle_branch_code"),
                    models.UniqueConstraint(condition=models.Q(("standalone_sku__isnull", False), models.Q(("standalone_sku", ""), _negated=True)), fields=("branch", "standalone_sku"), name="uniq_bundle_branch_standalone_sku_non_empty"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductBundleLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.productbundle"),
                ),
                (
                    "component_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bundle_components",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["bundle"], name="inventory_pr_bundle__0c36d7_idx"), models.Index(fields=["component_product"], name="inventory_pr_compone_0015db_idx")],
                "constraints": [models.UniqueConstraint(fields=("bundle", "component_product"), name="uniq_bundle_component_product")],
            },
        ),
    ]
