# Generated by Django 5.1.4 on 2026-03-06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_email_ci_unique'),
        ('inventory', '0013_productbundle_and_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to='purchase-imports/')),
                ('source_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], max_length=8)),
                ('state', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('review', 'Review'), ('applied', 'Applied'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('parse_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detected_columns', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('parsed_rows', models.JSONField(blank=True, default=list)),
                ('row_actions', models.JSONField(blank=True, default=dict)),
                ('apply_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchaseimportjob',
            index=models.Index(fields=['branch', 'state', 'created_at'], name='inventory_pu_branch__fc14b2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseimportjob',
            index=models.Index(fields=['branch', 'file_type', 'created_at'], name='inventory_pu_branch__f116e7_idx'),
        ),
    ]
