# Generated by Django 6.0.1 on 2026-03-06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_purchaseimportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseimportjob",
            name="format_signature",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="purchaseimportjob",
            name="supplier",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.supplier"),
        ),
        migrations.AddIndex(
            model_name="purchaseimportjob",
            index=models.Index(fields=["branch", "supplier", "format_signature"], name="inventory_pu_branch__eab1de_idx"),
        ),
        migrations.CreateModel(
            name="SupplierImportResolvedMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("format_signature", models.CharField(max_length=128)),
                ("key_type", models.CharField(choices=[("barcode", "Barcode"), ("supplier_sku", "Supplier SKU"), ("internal_sku", "Internal SKU"), ("normalized_name", "Normalized Name")], max_length=32)),
                ("key_value", models.CharField(max_length=255)),
                ("confidence", models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.branch")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.product")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.supplier")),
            ],
            options={
                "indexes": [models.Index(fields=["branch", "supplier", "format_signature"], name="inventory_su_branch__2377e1_idx"), models.Index(fields=["branch", "supplier", "key_type", "key_value"], name="inventory_su_branch__643c8b_idx")],
                "constraints": [models.UniqueConstraint(fields=("branch", "supplier", "format_signature", "key_type", "key_value"), name="uniq_supplier_import_resolved_mapping")],
            },
        ),
    ]
