# Generated by Django 6.0.1 on 2026-02-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoice_balance_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashshift',
            new_name='sales_cashs_branch__c95ed4_idx',
            old_name='sales_cashsh_branch__e09d5c_idx',
        ),
        migrations.RenameIndex(
            model_name='cashshift',
            new_name='sales_cashs_cashier_442523_idx',
            old_name='sales_cashsh_cashier_8176c2_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='sales_custo_branch__9cbb0d_idx',
            old_name='customer_branch_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='sales_custo_branch__ea3765_idx',
            old_name='customer_branch_email_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='sales_invoi_branch__063747_idx',
            old_name='invoice_branch_created_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='sales_invoi_status_027c24_idx',
            old_name='invoice_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceline',
            new_name='sales_invoi_invoice_c1a96c_idx',
            old_name='invoiceline_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceline',
            new_name='sales_invoi_product_fc6689_idx',
            old_name='invoiceline_product_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='sales_payme_invoice_be34bc_idx',
            old_name='payment_invoice_paid_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='sales_refun_return__c61805_idx',
            old_name='refund_return_refunded_idx',
        ),
        migrations.RenameIndex(
            model_name='return',
            new_name='sales_retur_invoice_f0a962_idx',
            old_name='return_invoice_created_idx',
        ),
        migrations.RenameIndex(
            model_name='return',
            new_name='sales_retur_branch__15feaf_idx',
            old_name='return_branch_created_idx',
        ),
        migrations.RenameIndex(
            model_name='returnline',
            new_name='sales_retur_return__c3a342_idx',
            old_name='returnline_return_txn_idx',
        ),
        migrations.RenameIndex(
            model_name='returnline',
            new_name='sales_retur_invoice_4fd9b8_idx',
            old_name='returnline_invoice_line_idx',
        ),
    ]
