# Generated by Django 5.1.1 on 2026-03-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_productbundle_and_lines"),
        ("sales", "0007_customer_pricing_mode_and_invoiceline_quantity_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="margin_warning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="product_bundle",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="inventory.productbundle"),
        ),
    ]
