# Generated by Django 5.1.1 on 2026-03-06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_productbundle_and_lines"),
        ("sales", "0008_invoiceline_bundle_margin_warning"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "segment",
                    models.CharField(
                        blank=True,
                        choices=[("package", "Package"), ("retail", "Retail"), ("vip", "VIP")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.branch")),
            ],
            options={
                "indexes": [models.Index(fields=["branch", "segment", "is_active"], name="sales_price_branch__ff9b34_idx")],
                "constraints": [models.UniqueConstraint(fields=("branch", "name"), name="uniq_price_list_branch_name")],
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("unit_type", models.CharField(choices=[("package", "Package"), ("unit", "Unit")], default="unit", max_length=16)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("effective_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_list",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="sales.pricelist"),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="price_list_items", to="inventory.product"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["price_list", "product", "unit_type"], name="sales_price_price_l_81966e_idx"),
                    models.Index(fields=["effective_from", "effective_to"], name="sales_price_effecti_1de8e9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceChangeAudit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("created", "Created"), ("updated", "Updated")], max_length=16)),
                ("old_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.branch")),
                (
                    "price_list_item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="change_logs", to="sales.pricelistitem"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["branch", "created_at"], name="sales_price_branch__6dc17d_idx"),
                    models.Index(fields=["price_list_item", "created_at"], name="sales_price_price_l_57083f_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="price_list",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="customers", to="sales.pricelist"),
        ),
        migrations.AddField(
            model_name="customer",
            name="segment",
            field=models.CharField(choices=[("package", "Package"), ("retail", "Retail"), ("vip", "VIP")], default="retail", max_length=16),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="price_source",
            field=models.CharField(
                choices=[("customer_specific", "Customer specific"), ("price_list", "Price list"), ("default", "Default")],
                default="default",
                max_length=32,
            ),
        ),
    ]
